import Head from 'next/head';

export default function Privacy() {
    return (
        <div className="bodyContainer">
            <p align="justify">Seedbox Philippines is a service offered by ATR Asset Management, Inc. (ATRAM) to enable people to invest in mutual funds online. Users on the platform are asked to provide personal information, which is then used by ATRAM and other interested parties in the course of operations.</p>
            <p align="justify">While our collection and use of this data is mandated by regulation, we believe that we must be transparent with our users regarding how it is managed on our platforms. Further, we believe we must be clear regarding what rights and responsibilities users have regarding their data.</p>
            <p align="justify">This Data Privacy Policy is considered an integral part of our Terms of Service.</p>
            <p align="justify" style={{marginBottom: 0}}><b>This Privacy Policy explains:</b></p>
            <ol type={1} style={{listStyleType: 'none', paddingLeft: 0}}>
            <li align="justify">What information is gathered, stored and used by Seedbox Philippines, and for what purpose;</li>
            <li align="justify">What rights and what responsibilities you have as a user regarding your personal data; and</li>
            <li align="justify">What recourse you have to amend, delete or withdraw your consent regarding your data.</li>
            </ol> 
            <p align="justify" style={{marginBottom: 0}}><b>User data gathered on our platforms consists of two types of information:</b></p>
            <ol type={1} style={{listStyleType: 'none', paddingLeft: 0}}>
            <li><p align="justify">Information volunteered by users as part of the registration, KYC and ordering processes, which may include data regarding their permanent residence address, family relationships, and financial circumstances. Users can see what information they have volunteered through the relevant section in their Accounts screens or pages. The collection of this data is mandated by government regulations and may not be waived.</p></li>
            <li><p align="justify">Information generated by users as a result of interacting with our platforms. This may include data such as Internet Protocol addresses, portfolio composition and value, and technical data regarding user mobile devices. We use this data to ensure that our systems are running smoothly.</p></li>
            </ol> 
            <p align="justify" style={{marginBottom: 0}}><b>User data is collated and organized by user account. You may request a copy of your data at any time by submitting a written request to:</b></p>
            <ul style={{listStyleType: 'none', paddingLeft: 0, marginTop: 0}}>
            <li><b>ATR Asset Management, Inc.</b></li>
            <li><b>Units A&amp;D, 8th Floor, 8 Rockwell</b></li>
            <li><b>8 Rockwell</b></li>
            <li><b>Rockwell Drive, Rockwell Center</b></li>
            <li><b>1210 Makati City, Philippines</b></li>
            </ul>
            <p align="justify">Please note that we will require proof of identity before releasing any information.</p>
            <p align="justify">We are also obliged to contact users periodically to confirm that KYC is up-to-date and accurate, and reserve the right to do so as a part of normal operations. Users are expected to provide accurate and truthful information and to update us of relevant changes.</p>
            <p align="justify">Users are encouraged to update and amend their volunteered information through the functionalities built into the Seedbox Philippines platforms.</p>
            <p align="justify">Users who choose to close their accounts with Seedbox Philippines are assumed to no longer wish to use the service. However, the laws of the Republic of the Philippines require that we maintain information relevant to financial transactions for up to five years after their settlement dates. We therefore cannot delete user information from our platform until after five years have passed. For the sake of convenience, we date this period from when the user closes their Seedbox Philippines account.</p>
            <p align="justify">Also, closing accounts with Seedbox Philippines does not automatically trigger redemption or account closure with relevant fund providers, wallet providers and other third parties. Users must still process redemptions and account closures with these third parties.</p>
            <p align="justify" style={{fontSize: '17px', marginBottom: '7px'}}><b>WAIVER OF DATA PRIVACY</b></p>
            <p align="justify">Because Seedbox Philippines is simply a distribution service, fund providers whose funds are available through the platforms will also require access to this data. Similarly, third party software providers for wallet and other stored value solutions may require access to this data as part of their mandated registration and KYC process. To simplify the process of signing up with these third parties, we ask users for their permission to provide the data they have already volunteered on our platform with the relevant third parties. This consent is never assumed, and is always solicited within the proper context of our operations. However, Seedbox Philippines has no say in how user data is managed, stored or used in third party systems.</p>
            <p align="justify">By signing up and agreeing to the Terms of Use of Seedbox Philippines, you, the user, thereby authorize the transfer, disclosure and communication of any information relating to his/her/their Account, or any information thereon, or any of his investments with ATR Asset Management, Inc. to any of the offices, branches, subsidiaries, affiliates, parent, agents and representatives, for use in connection with the provision of any service or product relating to your accounts or investments and for data processing and storage, customer satisfaction surveys, anti-money laundering monitoring, review and reporting, statistical, creditÂ&nbsp; and risk analysis and risk management purposes. In addition to the foregoing, ATR Asset Management, Inc,. and any branch, subsidiary, affiliate, parent, agent, representative or third party may transfer and disclose any such information as may be required by any law or regulation.</p>
        </div>
    );
}